name: flutter_dev_graph
description: A CLI tool to visualize Flutter/Dart project dependencies as a graph.
version: 0.0.1
repository: https://github.com/your-username/flutter_dev_graph

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

executables:
  fdg: fdg

dependencies:
  args: ^2.7.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
